#!/usr/bin/env python3
"""Build per-hole mental walkthroughs for a course.

    python3 scripts/course_walkthrough.py                        # every course
    python3 scripts/course_walkthrough.py paradise-pointe-posse
    python3 scripts/course_walkthrough.py --no-audio             # text only

Input   knowledge/golf/mental-training/courses/<slug>.json
Output  knowledge/golf/mental-training/walkthroughs/<slug>/h01.md   (the script)
        assets/audio/mental-training/courses/<slug>/h01.mp3         (the audio)
        knowledge/golf/mental-training/walkthroughs/<slug>/manifest.json
        plus the baked walkthrough block inside index.html

Audio goes through scripts/mental_training_tts.py, so the walkthroughs come out
in the same voice, at the same speaking rate, with the same pause handling as
the six sessions. --no-audio writes the text and the manifest and skips the
render, which is what you want on a box with no credentials: the hub reads its
text from the baked block, so the walkthroughs are usable with no audio at all.

WHAT THIS SCRIPT WILL NOT DO. It never invents a hole. Every fact it speaks -
par, yardage, where the bunkers are, which way the green falls - comes from the
course JSON, which scripts/extract_course_holes.py lifts from the committed
osm-course-book output. A field that is empty in the JSON produces no sentence
at all rather than a plausible one, and the hole is reported as a gap. The two
strategy fields the extractor derives (fat_side, ideal_leave) are marked
`derived` in the JSON and are phrased here as the conservative default they
are, not as local knowledge.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mental_training_tts as tts   # noqa: E402

REPO = Path(__file__).resolve().parent.parent
COURSE_DIR = REPO / "knowledge" / "golf" / "mental-training" / "courses"
TEXT_DIR = REPO / "knowledge" / "golf" / "mental-training" / "walkthroughs"
AUDIO_ROOT = REPO / "assets" / "audio" / "mental-training" / "courses"
INDEX = REPO / "index.html"

BEGIN = "  /* MENTAL-TRAINING:BEGIN - generated by scripts/course_walkthrough.py */"
END = "  /* MENTAL-TRAINING:END */"

SESSION_DIR = REPO / "knowledge" / "golf" / "mental-training"
INTRO_SLUG = "00-how-to-use"        # intro text at the top, not a session card

# The only sensory detail that is allowed in the opening line, because it is
# the only course-level detail that is verified (see 00-how-to-use.md). A slug
# that is not listed gets a neutral anchor rather than a borrowed one.
ANCHORS = {
    "paradise-pointe-posse":
        "bluegrass underfoot and the lake showing through the trees",
    "paradise-pointe-outlaw":
        "tight zoysia underfoot and the breeze coming off the lake",
}
NEUTRAL_ANCHOR = "the turf underfoot and the air on your face"


def _sentence(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if text and text[-1] not in ".!?":
        text += "."
    return text[0].upper() + text[1:] if text else text


def _wedge_finish(ideal_leave: str) -> bool:
    """Wedge land-spot ending, or ghost-circle lag ending?"""
    return bool(re.search(r"wedge|degree", ideal_leave or "", re.I))


_ORDINALS = ["", "first", "second", "third", "fourth", "fifth", "sixth",
             "seventh", "eighth", "ninth", "tenth", "eleventh", "twelfth",
             "thirteenth", "fourteenth", "fifteenth", "sixteenth",
             "seventeenth", "eighteenth"]


def _ordinal(n: int) -> str:
    """`the first tee`, not `the 1 tee` - this text is read aloud."""
    return _ORDINALS[n] if 0 < n < len(_ORDINALS) else str(n)


def _green_target(fat: str) -> str:
    """A green-relative aim point for the approach sentence.

    On a hole where the dominant hazard is a lateral penalty area, `fat_side`
    describes the TEE shot ("right side of the fairway") and cannot be dropped
    into a sentence about the approach. Those holes fall back to the generic
    fat side, which is what the sessions call it anyway.
    """
    return fat if "green" in fat else "fat side of the green"


def hole_markdown(course: str, slug: str, tees: str, h: dict) -> str:
    """One hole, 60 to 90 seconds, second person, present tense."""
    n, par, yds = h["hole"], h["par"], h["yardage"]
    trouble = (h.get("trouble") or "").strip()
    fat = (h.get("fat_side") or "").strip()
    leave = (h.get("ideal_leave") or "").strip()
    green = (h.get("green_notes") or "").strip()
    shape = (h.get("shape") or "").strip()
    anchor = ANCHORS.get(slug, NEUTRAL_ANCHOR)

    L: list[str] = ["# Hole %d - %s" % (n, course), ""]

    # 1 - on the tee, one sensory anchor. The par and the number live here and
    # nowhere else; a standalone yardage line above would be read out twice.
    open_line = ("You are on the %s tee. Par %d, %d yards from the %s tees. "
                 "Feel %s." % (_ordinal(n), par, yds, tees, anchor))
    if shape:
        open_line += " The hole %s." % shape
    L += [_sentence(open_line), ""]

    # 2 - the backward plan.
    if par == 3:
        L += [_sentence("Play it backward. There is one shot here and it is "
                        "this one, so the plan is simply %s" % leave), ""]
    else:
        L += [_sentence("Play it backward. You want %s, so the tee shot only "
                        "has to put you on that number. Nothing more." % leave),
              ""]

    # 3 - the one place the ball cannot go, and the target that keeps a normal
    #     miss safe. Silence here when the pipeline tagged no hazard.
    if trouble:
        L += [_sentence("Here is the one place the ball cannot go: %s. So the "
                        "target is the %s. Aim there and a normal miss is "
                        "still grass." % (trouble, fat)), ""]
    else:
        L += [_sentence("No penalty area or bunker is mapped on this hole, so "
                        "nothing here can cost you a stroke except a lazy "
                        "target. Pick the %s and commit anyway." % fat), ""]

    # 4 - the six-step routine, compressed.
    L += [_sentence("Now the routine, compressed. Decide, behind the ball. "
                    "One target, not a zone. See the full flight, launch to "
                    "landing. Feel one rehearsal swing at that tempo. Walk in, "
                    "one look, and go. Then accept it, whatever it does."), ""]

    L += ["> Pause.", ""]

    # 5 - the approach, to the fat side.
    if par == 3:
        L += [_sentence("Watch the ball land on the %s, take its hop, and "
                        "settle." % _green_target(fat)), ""]
    else:
        L += [_sentence("Now the approach. The pin does not matter yet, the %s "
                        "does. Same routine, committed swing, ball finishing "
                        "right there." % _green_target(fat)), ""]

    # 6 - the finish that matches the leave.
    if green:
        L += [_sentence("The green: %s" % green), ""]
    if _wedge_finish(leave) and par != 3:
        L += [_sentence("You have the wedge you planned for. Pick your landing "
                        "spot, a patch the size of a towel, and see the ball "
                        "land on it, hop once, and trickle to tap-in range."),
              ""]
    else:
        L += [_sentence("Draw the ghost circle, three feet around the hole. "
                        "Read it from the low side. Lag it dead, dying inside "
                        "the circle."), ""]

    # 7 - the ball in the cup, and one breath.
    L += [_sentence("Hear the ball drop into the cup. One breath. Walk to the "
                    "next tee with nothing carried over."), ""]

    return "\n".join(L).rstrip() + "\n"


def build_course(slug: str, do_audio: bool, force: bool) -> tuple[dict, list[str]]:
    src = COURSE_DIR / ("%s.json" % slug)
    if not src.exists():
        raise SystemExit("no course JSON at %s" % src)
    doc = json.loads(src.read_text(encoding="utf-8"))
    course, tees = doc["course"], doc.get("tees", "")

    text_dir = TEXT_DIR / slug
    audio_dir = AUDIO_ROOT / slug
    text_dir.mkdir(parents=True, exist_ok=True)

    gaps: list[str] = []
    entries = []
    for h in doc.get("holes", []):
        n = h["hole"]
        md = hole_markdown(course, slug, tees, h)
        (text_dir / ("h%02d.md" % n)).write_text(md, encoding="utf-8")

        missing = [k for k in ("trouble", "shape", "green_notes")
                   if not (h.get(k) or "").strip()]
        # One gap per field, not one per hole: a hole missing both `trouble`
        # and `shape` used to be filed under shape alone and the missing
        # hazard map never showed up in the report.
        for k in missing:
            gaps.append((k, n))

        audio_rel = "assets/audio/mental-training/courses/%s/h%02d.mp3" % (slug, n)
        entry = {
            "hole": n, "par": h["par"], "yardage": h["yardage"],
            "text": md, "audio": audio_rel, "audio_built": False,
            "derived": bool(h.get("derived")),
            "gaps": missing,
        }

        if do_audio:
            out = audio_dir / ("h%02d.mp3" % n)
            try:
                tts.HASH_DIR = audio_dir / ".hashes"
                status = tts.render_markdown(
                    text_dir / ("h%02d.md" % n), out, force=force)
                entry["audio_built"] = True
                entry["duration"] = tts.describe(out)
                print("   hole %-2d %-9s %s" % (n, status, entry["duration"]))
            except tts.TTSError as e:
                print("   hole %-2d audio FAILED  %s" % (n, e))
        entries.append(entry)

    manifest = {
        "course": course, "slug": slug, "tees": tees,
        "source": doc.get("source", ""),
        "holes": [{k: v for k, v in e.items() if k != "text"} for e in entries],
    }
    (text_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return {"course": course, "slug": slug, "tees": tees,
            "holes": entries}, gaps


# ---------------------------------------------------------------------------
# Bake the text into the hub
# ---------------------------------------------------------------------------

def _run_time(slug: str) -> str:
    """The row's run time, measured off the rendered MP3 rather than claimed.

    The scripts used to open with a hand-written "Run time about N minutes",
    which was a placeholder and read 8 to 12 minutes against audio that runs
    under four - the figure described the exercise, pauses and all, not the
    track. Measuring the file is the only version that cannot drift: re-render
    at a different speaking rate and this follows it. No MP3 yet (a text-only
    build, or before the first render) returns "" and the caller falls back to
    the goal sentence, so nothing claims a run time it cannot back up.
    """
    mp3 = REPO / "assets" / "audio" / "mental-training" / ("%s.mp3" % slug)
    if not mp3.exists():
        return ""
    secs = tts.mp3_duration(mp3.read_bytes())
    return "Run time %d:%02d" % (int(secs // 60), int(secs % 60))


def _sessions() -> list[dict]:
    """The six session scripts, plus the intro, straight from the markdown."""
    out = []
    for md in sorted(SESSION_DIR.glob("*.md")):
        text = md.read_text(encoding="utf-8")
        m = re.search(r"^#\s+(.+)$", text, re.M)
        title = m.group(1).strip() if m else md.stem
        # The row's subtitle is the measured run time. Failing that - no audio
        # built yet - it is the first sentence of the lead paragraph, which is
        # the session's goal.
        body = re.sub(r"^#\s+.+$", "", text, count=1, flags=re.M).strip()
        first = body.split("\n\n")[0].replace("\n", " ").strip()
        sub = _run_time(md.stem) or (first.split(". ")[0].strip(" .")
                                     if first else "")
        out.append({
            "slug": md.stem,
            "title": title,
            "sub": sub,
            "intro": md.stem == INTRO_SLUG,
            "audio": "assets/audio/mental-training/%s.mp3" % md.stem,
            "text": text,
        })
    return out


def inject(courses: list[dict]) -> None:
    """Write the Mental Training text into index.html between the markers.

    The hub is one self-contained file that has to work with no network, so the
    session scripts and the walkthrough text live in the page rather than
    behind a fetch. Only the audio needs the network, and each player removes
    itself when its file is not there - which is the state until the render
    runs on a box with credentials.
    """
    payload = {
        "sessions": _sessions(),
        "courses": [{
            "slug": c["slug"], "course": c["course"], "tees": c["tees"],
            "holes": [{"hole": h["hole"], "par": h["par"],
                       "yardage": h["yardage"], "audio": h["audio"],
                       "text": h["text"]}
                      for h in c["holes"]],
        } for c in courses],
    }

    block = "%s\n  var MENTAL_TRAINING=%s;\n%s" % (
        BEGIN, json.dumps(payload, separators=(",", ":")), END)

    src = INDEX.read_text(encoding="utf-8")
    if BEGIN in src and END in src:
        start, stop = src.index(BEGIN), src.index(END) + len(END)
        src = src[:start] + block + src[stop:]
    else:
        raise SystemExit(
            "index.html has no MENTAL-TRAINING:BEGIN / END markers - add them "
            "inside the app script before running with injection")
    INDEX.write_text(src, encoding="utf-8")
    holes = sum(len(c["holes"]) for c in payload["courses"])
    print("\nbaked %d sessions and %d holes across %d courses into index.html "
          "(%.0f KB)" % (len(payload["sessions"]), holes,
                         len(payload["courses"]), len(block) / 1024))


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("slugs", nargs="*", help="course slugs; default is all")
    ap.add_argument("--no-audio", action="store_true",
                    help="write text and manifest only, skip the TTS render")
    ap.add_argument("--no-inject", action="store_true",
                    help="do not touch index.html")
    ap.add_argument("--force", action="store_true",
                    help="re-render audio even when the script is unchanged")
    args = ap.parse_args(argv[1:])

    slugs = args.slugs or sorted(p.stem for p in COURSE_DIR.glob("*.json"))
    if not slugs:
        print("no course JSON in %s - run scripts/extract_course_holes.py first"
              % COURSE_DIR)
        return 1

    built, all_gaps = [], {}
    for slug in slugs:
        print("%s" % slug)
        course, gaps = build_course(slug, not args.no_audio, args.force)
        built.append(course)
        all_gaps[slug] = gaps
        print("   %d holes written to %s"
              % (len(course["holes"]), (TEXT_DIR / slug).relative_to(REPO)))

    if not args.no_inject:
        inject(built)

    print("\nGAPS - fields the pipeline could not resolve, left empty rather "
          "than filled in:")
    for slug, gaps in all_gaps.items():
        if not gaps:
            print("  %s: none" % slug)
            continue
        byfield: dict[str, list[int]] = {}
        for field, n in gaps:
            byfield.setdefault(field, []).append(n)
        for field in ("shape", "trouble", "green_notes"):
            holes = byfield.get(field)
            if not holes:
                continue
            print("  %s: %s missing on %d hole%s (%s)"
                  % (slug, field, len(holes), "" if len(holes) == 1 else "s",
                     ", ".join(str(h) for h in holes)))

    if args.no_audio:
        total = 0
    else:
        total = sum(p.stat().st_size for p in AUDIO_ROOT.rglob("*.mp3"))
    print("\nwalkthrough audio total: %.1f MB" % (total / 1e6))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
